#
b D:\Ajith\CustomerInformation\Database\
#
d "Schema Area":6,64;1 D:\Ajith\CustomerInformation\Database\
#
d "Data Area":10,256;8 D:\Ajith\CustomerInformation\Database\
#
d "Index Area":20,32;8 D:\Ajith\CustomerInformation\Database\
#
d "LOB Area":30,32;8 D:\Ajith\CustomerInformation\Database\
#
d "Audit Data Area":40,256;8 D:\Ajith\CustomerInformation\Database\
#
d "Audit Index Area":50,32;8 D:\Ajith\CustomerInformation\Database\
#
d "Change Data Area":60,256;8 D:\Ajith\CustomerInformation\Database\
#
d "Change Index Area":70,32;8 D:\Ajith\CustomerInformation\Database\
#
e "Encryption Policy Area":80,32;8 D:\Ajith\CustomerInformation\Database\
